### ISSUE TITLE
[tests] urls are being changes when they have special characters like `.`

### ISSUE THREAD

**Issue by sarathm09** [sarathm09/vibranium#27]
Create a test with `.` in the url.
It gets converted to some random character during execution.

**Comment by rahulbhargav** [comment]
Hi @sarathm09 Can I take up this issue? 
Also, could you provide some more information regarding this issue?

**Comment by sarathm09** [comment]
@rahulbhargav Yes, sure!
The issue is that whenever we have any character like `.` in the URL, for example `this/is/an/example.html`, the `.` gets replaced with a random character.
This is happening [because of this line](https://github.com/sarathm09/vibranium/blob/0772e3bd84d427bee1689dd9fe20cf90da7cd16e/src/app/testexecutor.js#L433)

Though the functionality of replacing such characters were intentional (for example, you could specify `this/url/needs/random/characters/[A-Za-z]{5}` and it would dynamically generate a URL like `this/url/needs/random/characters/HsVyh`, ie replace _[A-Za-z]{5}_ with a string that matches the same pattern.), It causes issues in cases like `this/is/an/example.html`, where the characters should not be replaced.

So we need to either remove this functionality for the url, or somehow handle the characters in url separately.

**Comment by rahulbhargav** [comment]
Hi @sarathm09 Thanks for providing more info. 

From what I understood after going through some code, [this line here](https://github.com/sarathm09/vibranium/blob/master/src/app/testexecutor.js#L406) is responsible for replacing the `.` character with randomly generated character. And we want to avoid that. 

For this I think we can do three approaches: 
1. Add `.` in the list of characters that are being escaped before replacing the placeholder [here](https://github.com/sarathm09/vibranium/blob/master/src/app/testexecutor.js#L430). This would work for cases like in the above mentioned example. But there could be regular expressions with `.` character in them which would be escaped. 
2. As you mentioned above, remove the dynamic generation of string feature for url. But, I'm not sure if backward compatibility would be an issue here. 
3. Another option is to introduce a pattern for providing regex as a part of string. For example: 
    Instead of accepting the regex inside url like `.../characters/[A-Za-z]{5}` we can introduce regex inside special characters like `$|     |$`. So, the URL would look like `.../characters/$|[A-Za-z]{5}|$`. This way, we can pattern match for enclosing characters to identify the regular expressions provided by the user. Other than these enclosed sub-strings, we can escape all other URL specific characters from URLs. But, again, I'm not sure if backward compatibility would be an issue here.  
 
Please provide your thoughts on the above mentioned approaches.

**Comment by sarathm09** [comment]
Hi @rahulbhargav 

Regarding 1, as you mentioned, it'll cause an issue when there is a `.` meant to be used as a regex.

I'm actually in favour of 2. If a regex is needed, they can be generated using `variables` and used. But then again backward compatibility is an issue, but from what I've seen, having regex in the URL is not something that is preferred.

As for 3, I like the approach, but I feel that it then becomes a bit inconsistent and confusing as the syntax changes based on where you define the regex.
